Repository f-lab-edu/show-ticketing-service, pull requests merged in 2021-05, with the labels that each got.

#94 [#93] 공연 상세 정보 조회 기능 수정 및 기능 추가
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/service/SeatPriceService.java
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
Labels: feedback wanted

#99 [#98] 공연 상세 정보 조회 스케줄 id 추가
  src/main/java/com/show/showticketingservice/model/performance/PerformanceTimeResponse.java
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
Labels: feedback wanted, ongoing

#97 [#84] 공연 리스트 조회
  src/main/java/com/show/showticketingservice/config/RedisCacheConfig.java
  src/main/java/com/show/showticketingservice/config/WebMvcConfig.java
  src/main/java/com/show/showticketingservice/controller/PerformanceController.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceMapper.java
  src/main/java/com/show/showticketingservice/model/criteria/PerformancePagingCriteria.java
  src/main/java/com/show/showticketingservice/model/performance/PerformancePeriod.java
  src/main/java/com/show/showticketingservice/model/performance/PerformanceResponse.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/tool/constants/CacheConstant.java
  src/main/java/com/show/showticketingservice/tool/converter/StringToShowTypeConverter.java
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
  src/test/java/com/show/showticketingservice/service/PerformanceServiceTest.java
Labels: feedback wanted, ongoing

#102 [#74] 찜 목록 조회 기능 구현
  src/main/java/com/show/showticketingservice/config/RedisCacheConfig.java
  src/main/java/com/show/showticketingservice/controller/PickController.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceMapper.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/service/PickService.java
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
  src/test/java/com/show/showticketingservice/service/PickServiceTest.java
Labels: feedback wanted

#103 다중 찜 목록 삭제 기능 구현
  src/main/java/com/show/showticketingservice/controller/PickController.java
  src/main/java/com/show/showticketingservice/mapper/PickMapper.java
  src/main/java/com/show/showticketingservice/service/PickService.java
  src/main/resources/mybatis/mappers/PickMapper.xml
  src/test/java/com/show/showticketingservice/service/PickServiceTest.java
Labels: feedback wanted

#100 [#75] 공연 스케줄, 잔여 좌석 조회
  src/main/java/com/show/showticketingservice/config/RedisCacheConfig.java
  src/main/java/com/show/showticketingservice/controller/PerformanceController.java
  src/main/java/com/show/showticketingservice/exception/performance/PerformanceTimeNotExistsException.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceMapper.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceTimeMapper.java
  src/main/java/com/show/showticketingservice/model/performance/PerfTimeAndRemainingSeatsResponse.java
  src/main/java/com/show/showticketingservice/model/performance/PerformanceTitleAndTimesResponse.java
  src/main/java/com/show/showticketingservice/model/performance/RemainingSeatsResponse.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/tool/advice/PerformanceExceptionAdvice.java
  src/main/java/com/show/showticketingservice/tool/constants/CacheConstant.java
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
  src/main/resources/mybatis/mappers/PerformanceTimeMapper.xml
  src/test/java/com/show/showticketingservice/service/PerformanceServiceTest.java
Labels: feedback wanted

#108 [#107] 공연 스케줄 시간 체크 로직 수정
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
Labels: modification

#105 [#72] 공연 검색 기능 구현
  src/main/java/com/show/showticketingservice/controller/SearchController.java
  src/main/java/com/show/showticketingservice/exception/performance/NoKeywordException.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceMapper.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/tool/advice/PerformanceExceptionAdvice.java
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
  src/test/java/com/show/showticketingservice/service/PerformanceServiceTest.java
Labels: feedback wanted

#104 [#76] 상세 좌석 조회
  src/main/java/com/show/showticketingservice/config/DataSourceConfig.java
  src/main/java/com/show/showticketingservice/config/MyBatisConfig.java
  src/main/java/com/show/showticketingservice/config/RedisCacheConfig.java
  src/main/java/com/show/showticketingservice/controller/SearchController.java
  src/main/java/com/show/showticketingservice/controller/SeatController.java
  src/main/java/com/show/showticketingservice/exception/performance/NoKeywordException.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceMapper.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceTimeMapper.java
  src/main/java/com/show/showticketingservice/mapper/SeatMapper.java
  src/main/java/com/show/showticketingservice/mapper/SeatPriceMapper.java
  src/main/java/com/show/showticketingservice/mapper/UserMapper.java
  src/main/java/com/show/showticketingservice/mapper/VenueHallMapper.java
  src/main/java/com/show/showticketingservice/mapper/VenueMapper.java
  src/main/java/com/show/showticketingservice/model/enumerations/DatabaseServer.java
  src/main/java/com/show/showticketingservice/model/seat/SeatAndPriceResponse.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/service/PickService.java
  src/main/java/com/show/showticketingservice/service/SeatPriceService.java
  src/main/java/com/show/showticketingservice/service/SeatService.java
  src/main/java/com/show/showticketingservice/service/SessionLoginService.java
  src/main/java/com/show/showticketingservice/service/UserService.java
  src/main/java/com/show/showticketingservice/service/VenueHallService.java
  src/main/java/com/show/showticketingservice/service/VenueService.java
  src/main/java/com/show/showticketingservice/tool/advice/PerformanceExceptionAdvice.java
  src/main/java/com/show/showticketingservice/tool/advice/SeatExceptionAdvice.java
  src/main/java/com/show/showticketingservice/tool/constants/CacheConstant.java
  src/main/java/com/show/showticketingservice/tool/util/datasource/RoutingDataSource.java
  src/main/resources/application-local.properties
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
  src/main/resources/mybatis/mappers/PerformanceTimeMapper.xml
  src/main/resources/mybatis/mappers/SeatMapper.xml
  src/test/java/com/show/showticketingservice/service/PerformanceServiceTest.java
  src/test/java/com/show/showticketingservice/service/SeatServiceTest.java
Labels: feedback wanted
