Repository f-lab-edu/show-ticketing-service, pull requests merged in 2021-04, with the labels that each got.

#68 [#65] 공연 스케줄 입력 시 해당 공연에 대한 좌석 데이터 생성
  etc/show_ticketing_service.sql
  src/main/java/com/show/showticketingservice/exception/performance/SeatPriceNotExistsException.java
  src/main/java/com/show/showticketingservice/mapper/SeatMapper.java
  src/main/java/com/show/showticketingservice/mapper/SeatPriceMapper.java
  src/main/java/com/show/showticketingservice/mapper/VenueHallMapper.java
  src/main/java/com/show/showticketingservice/model/performance/PerformanceTimeRequest.java
  src/main/java/com/show/showticketingservice/model/performance/SeatPriceRowNumData.java
  src/main/java/com/show/showticketingservice/model/performance/SeatRequest.java
  src/main/java/com/show/showticketingservice/model/venueHall/VenueHallColumnSeat.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/service/SeatPriceService.java
  src/main/java/com/show/showticketingservice/service/VenueHallService.java
  src/main/java/com/show/showticketingservice/tool/advice/PerformanceExceptionAdvice.java
  src/main/resources/mybatis/mappers/PerformanceTimeMapper.xml
  src/main/resources/mybatis/mappers/SeatMapper.xml
  src/main/resources/mybatis/mappers/SeatPriceMapper.xml
  src/main/resources/mybatis/mappers/VenueHallMapper.xml
Labels: help wanted

#81 [#61] 공연 상세 정보 조회
  src/main/java/com/show/showticketingservice/config/RedisCacheConfig.java
  src/main/java/com/show/showticketingservice/controller/PerformanceController.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceMapper.java
  src/main/java/com/show/showticketingservice/model/performance/PerformanceDetailInfoResponse.java
  src/main/java/com/show/showticketingservice/model/performance/PerformanceTimeResponse.java
  src/main/java/com/show/showticketingservice/model/performance/SeatPriceResponse.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/tool/constants/CacheConstant.java
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
Labels: feedback wanted

#83 [#82] 공연장, 공연 홀을 수정 시 이미 존재하는 동일한 이름이 있는지 체크 기능 수정
  src/main/java/com/show/showticketingservice/mapper/VenueMapper.java
  src/main/java/com/show/showticketingservice/service/VenueService.java
  src/main/resources/mybatis/mappers/VenueHallMapper.xml
  src/main/resources/mybatis/mappers/VenueMapper.xml
  src/test/java/com/show/showticketingservice/service/VenueServiceTest.java
Labels: feedback wanted

#88 [#85] 공연 상세 정보 이미지 조회
  src/main/java/com/show/showticketingservice/model/performance/PerformanceDetailInfoResponse.java
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
Labels: feedback wanted

#86 [#36] 공연 정보 삭제 기능 구현
  etc/show_ticketing_service.sql
  src/main/java/com/show/showticketingservice/controller/PerformanceController.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceMapper.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/resources/mybatis/mappers/PerformanceMapper.xml
Labels: feedback wanted

#92 [#90] UserSession에 저장되는 userId 속성 변경
  src/main/java/com/show/showticketingservice/mapper/UserMapper.java
  src/main/java/com/show/showticketingservice/model/user/UserSession.java
  src/main/java/com/show/showticketingservice/service/SessionLoginService.java
  src/main/java/com/show/showticketingservice/service/UserService.java
  src/main/resources/mybatis/mappers/UserMapper.xml
  src/test/java/com/show/showticketingservice/controller/MyPageControllerTest.java
  src/test/java/com/show/showticketingservice/controller/UserControllerTest.java
  src/test/java/com/show/showticketingservice/controller/VenueControllerTest.java
Labels: Priority: Critical
