Repository f-lab-edu/show-ticketing-service, pull requests merged in 2021-06, with the labels that each got.

#112 [#111] Cache 관련 설정 수정
  src/main/java/com/show/showticketingservice/config/RedisCacheConfig.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/service/VenueService.java
  src/main/java/com/show/showticketingservice/tool/constants/CacheConstant.java
Labels: bug fix, feedback wanted, modification

#117 [#116] Jenkins CI 적용
  Jenkinsfile
  pom.xml
Labels: feedback wanted

#115 [#114] 공연 스케줄, 잔여 좌석 조회 응답 데이터 수정
  src/main/java/com/show/showticketingservice/controller/PerformanceController.java
  src/main/java/com/show/showticketingservice/mapper/PerformanceTimeMapper.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/test/java/com/show/showticketingservice/service/PerformanceServiceTest.java
Labels: feedback wanted, modification

#121 [#118] Jenkins CD 적용
  Jenkinsfile
Labels: feedback wanted

#120 [#119] 로그 버그 수정
  src/main/resources/application.properties
Labels: Priority: Critical, bug, feedback wanted, modification

#123 [#122] 배포 서버용 application 설정 파일 생성 및 적용
  pom.xml
  src/main/java/com/show/showticketingservice/config/DataSourceConfig.java
  src/main/java/com/show/showticketingservice/config/JasyptConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application-local.properties
  src/main/resources/application.properties
Labels: feedback wanted

#125 프로젝트 JDK 버전 변경
  Jenkinsfile
  pom.xml
  src/main/java/com/show/showticketingservice/exception/authentication/UserAlreadyLoggedInException.java
  src/main/java/com/show/showticketingservice/service/PerformanceService.java
  src/main/java/com/show/showticketingservice/service/SessionLoginService.java
  src/main/java/com/show/showticketingservice/tool/advice/AuthenticationExceptionAdvice.java
Labels: feedback wanted
